export const TRANSACTION_PAYMENT_TYPE_PAID_RECIPIENTS = 1;
export const TRANSACTION_PAYMENT_TYPE_PAID_SENDER = 3;

export const TRANSACTION_TYPE_RECEIVE = 1;
export const TRANSACTION_TYPE_SEND = 3;
export const TRANSACTION_TYPE_PAY_DEBIT = 5;
